In [ ]:
import json

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
with open("/content/drive/My Drive/Eng/ep_votes.json", "r") as read_file:
    raw_vote_data_in_json = json.load(read_file)

In [ ]:
len(raw_vote_data_in_json)
# Период с 2004 по 2020 время есть в ts первые 4 цифры этого год

24846

In [ ]:
for i in range(4400,4420):
  print(i,raw_vote_data_in_json[i]['ts'][:10])

4400 2008-07-08
4401 2008-06-19
4402 2008-06-18
4403 2008-06-05
4404 2008-06-17
4405 2008-07-09
4406 2008-09-24
4407 2008-07-10
4408 2008-06-19
4409 2008-07-08
4410 2008-09-24
4411 2008-06-18
4412 2008-07-09
4413 2008-06-05
4414 2008-07-10
4415 2008-06-17
4416 2008-06-19
4417 2008-09-24
4418 2008-06-18
4419 2008-07-08

In [ ]:
raw_vote_data_in_json[22564]['votes']['+']['groups']

In [ ]:
ter = []
for i in raw_vote_data_in_json[11122]['votes']['+']['groups']: 
    print(i)
    srtyyy = i 
    ter.append(i)

print(ter)

without_votes = []

ALDE
ECR
EFDD
GUE/NGL
NI
PPE
S&D
Verts/ALE
['ALDE', 'ECR', 'EFDD', 'GUE/NGL', 'NI', 'PPE', 'S&D', 'Verts/ALE']

In [ ]:
without_votes = []
def get_groups(vote_id,t):
  gr_list = []
  flag = -1
  try:
    for i in raw_vote_data_in_json[vote_id]['votes'][t]['groups']: 
      #print(i)     
      gr_list.append(i)
  except KeyError:
    flag = 1
  if (flag > -1):
    without_votes.append(vote_id) #  надо добавить удаление дупликатов!
  #cache_votes = list(dict.fromkeys(without_votes))
  #without_votes = cache_votes
  res_list=list(dict.fromkeys(gr_list))
  return res_list

In [ ]:
err_votes_nums=[]

In [ ]:
def get_num(vote_num): #сейчас она возвращает чисто лист депутатов для конкретного голосования без деления по голосам
  meps = []
  ter = get_groups(vote_num,'+')
  for gr in ter:
    for i in range(len(raw_vote_data_in_json[vote_num]['votes']['+']['groups'][gr][:])):
      try:
          meps.append(raw_vote_data_in_json[vote_num]['votes']['+']['groups'][gr][i]['mepid'])
      except KeyError:
          srtyy = 0
          err_votes_nums.append("+__"+str(i))
  ter = get_groups(vote_num,'-')
  for gr in ter:
    for i in range(len(raw_vote_data_in_json[vote_num]['votes']['-']['groups'][gr][:])):
      try:
          meps.append(raw_vote_data_in_json[vote_num]['votes']['-']['groups'][gr][i]['mepid'])
      except KeyError:
          srtyy = 0
          err_votes_nums.append("-__"+str(i))
  ter = get_groups(vote_num,'0')
  for gr in ter:
    for i in range(len(raw_vote_data_in_json[vote_num]['votes']['0']['groups'][gr][:])):
      try:
          meps.append(raw_vote_data_in_json[vote_num]['votes']['0']['groups'][gr][i]['mepid'])
      except KeyError:
          srtyy = 0
          err_votes_nums.append("0__"+str(i))   
  return meps

In [ ]:
def get_date_info(vote_num): #сейчас она возвращает чисто лист депутатов для конкретного голосования без деления по голосам
  meps = []
  ter = get_groups(vote_num,'+')
  for gr in ter:
    for i in range(len(raw_vote_data_in_json[vote_num]['votes']['+']['groups'][gr][:])):
      try:
          meps.append(raw_vote_data_in_json[vote_num]['votes']['+']['groups'][gr][i]['mepid'])
      except KeyError:
          srtyy = 0
          err_votes_nums.append("+__"+str(i))
  ter = get_groups(vote_num,'-')
  for gr in ter:
    for i in range(len(raw_vote_data_in_json[vote_num]['votes']['-']['groups'][gr][:])):
      try:
          meps.append(raw_vote_data_in_json[vote_num]['votes']['-']['groups'][gr][i]['mepid'])
      except KeyError:
          srtyy = 0
          err_votes_nums.append("-__"+str(i))
  ter = get_groups(vote_num,'0')
  for gr in ter:
    for i in range(len(raw_vote_data_in_json[vote_num]['votes']['0']['groups'][gr][:])):
      try:
          meps.append(raw_vote_data_in_json[vote_num]['votes']['0']['groups'][gr][i]['mepid'])
      except KeyError:
          srtyy = 0
          err_votes_nums.append("0__"+str(i))   
  return meps

In [ ]:
men = []
ser = []

In [ ]:
cache_votes = list(dict.fromkeys(without_votes))
without_votes = cache_votes

In [ ]:
def get_vote(mep_num,vote_num): #сейчас она возвращает чисто лист депутатов для конкретного голосования без деления по голосам
  res_data = 0
  ter = get_groups(vote_num,'+')
  for gr in ter:
    for i in range(len(raw_vote_data_in_json[vote_num]['votes']['+']['groups'][gr][:])):
      try:
        if (raw_vote_data_in_json[vote_num]['votes']['+']['groups'][gr][i]['mepid'] == mep_num):
          res_data = +1
      except KeyError:
        res_data=0
  ter = get_groups(vote_num,'-')
  for gr in ter:
    for i in range(len(raw_vote_data_in_json[vote_num]['votes']['-']['groups'][gr][:])):
      try:
        if (raw_vote_data_in_json[vote_num]['votes']['-']['groups'][gr][i]['mepid'] == mep_num):
          res_data = -1  
      except KeyError:
        res_data=0
  return res_data

In [ ]:
from datetime import datetime, timedelta
votes_delta = []
dates=[]
for i in range(0,24846):
  cur_date = raw_vote_data_in_json[i]['ts'][:10]
  if (cur_date >= '2004-07-01' and cur_date <= '2004-12-31'):
    #print(cur_date)
    if not(i in without_votes):
      votes_delta.append(i)
      dates.append(cur_date + " " + str(i))
print(len(votes_delta))

212

In [ ]:
men = []
ser = []
t = 0
for i in (votes_delta):
  tmp_men = get_num(i)
  men.append(list(tmp_men))
  if (len(tmp_men) == 0):
    t += 1
  ser.append(len(tmp_men))
print(len(men))

212

In [ ]:
deputates_delta = []
for i in range(len(votes_delta)):
  deputates_delta += men[i]
cache_votes = list(dict.fromkeys(deputates_delta))
deputates_delta = cache_votes
print(len(deputates_delta))
deputates_delta.sort()

732

In [ ]:
len(dates)

212

In [ ]:
dates[0:11]

In [ ]:
deputates_delta[0:10]

[1, 684, 729, 945, 966, 988, 997, 1002, 1018, 1023]

In [ ]:
get_vote(1,3713)

0

In [ ]:
df_ = pd.DataFrame(index=deputates_delta, columns=dates)
df_ = df_.fillna(0)

In [ ]:
df_.shape

(787, 475)

In [ ]:
for x, y in [(x,y) for x in deputates_delta for y in dates]:
    yd_=(y[11:])
    df_.at[x,y]=get_vote(x,int(yd_))

In [ ]:
df_.head(n=15)

      2004-09-15 161  2004-09-15 147  ...  2004-12-16 30  2004-12-16 41
1                  1               1  ...              1              1
234                1               1  ...              1              1
684                1               1  ...              1              1
729                1               1  ...              1              1
945                1               1  ...              1              1
966                1               1  ...             -1              1
997               -1              -1  ...             -1             -1
1002              -1               1  ...              1              1
1018               1               1  ...              1              1
1023               1               1  ...             -1              1
1026               0               0  ...              0              0
1037               1               1  ...              1              1
1038               0               0  ...              0              0
1040              -1              -1  ...              1              1
1055               1               1  ...              1              1

[15 rows x 212 columns]

In [ ]:
date_list = list(df_.columns)
only_date = list(map(lambda x: x[:10], date_list))

In [ ]:
new_df = df_.T

In [ ]:
new_df['date']= only_date

In [ ]:
new_df['date'] = new_df['date'].astype('datetime64[ns]')

In [ ]:
new_df=new_df.sort_values(by=['date'])

In [ ]:
df_ = new_df.drop( columns='date').T

In [ ]:
new_df.groupby('date').groups.keys()

dict_keys([Timestamp('2004-09-15 00:00:00'), Timestamp('2004-09-16 00:00:00'), Timestamp('2004-10-14 00:00:00'), Timestamp('2004-10-26 00:00:00'), Timestamp('2004-10-28 00:00:00'), Timestamp('2004-11-17 00:00:00'), Timestamp('2004-11-18 00:00:00'), Timestamp('2004-12-01 00:00:00'), Timestamp('2004-12-02 00:00:00'), Timestamp('2004-12-14 00:00:00'), Timestamp('2004-12-15 00:00:00'), Timestamp('2004-12-16 00:00:00')])

In [ ]:
df = new_df.groupby('date').get_group('2004-09-15')
df.loc[:, (df != 0).any(axis=0)]

                1  234  684  729  945  ...  29019  29073  29074  29579       date
2004-09-15 161  1    1    1    1    1  ...     -1      1      1      1 2004-09-15
2004-09-15 147  1    1    1    1    1  ...      1      1      1      1 2004-09-15
2004-09-15 174  1    1    1    0    1  ...      1      1      1      1 2004-09-15
2004-09-15 155  1    1    1    1    1  ...      1      0      1      1 2004-09-15
2004-09-15 170  1    1    1    0    1  ...      1      1      1      1 2004-09-15
2004-09-15 165  1    1    1    1    1  ...      0      1      1      1 2004-09-15

[6 rows x 620 columns]

In [ ]:

df = new_df.groupby('date').get_group('2004-09-15')
t = list(df.loc[:, (df != 0).any(axis=0)].columns)

In [ ]:
df = new_df.groupby('date').get_group('2004-10-14')
t2 = list(df.loc[:, (df != 0).any(axis=0)].columns)

In [ ]:
len(t)

620

In [ ]:
df_.to_excel("votes_.xlsx")

In [ ]:
#df_.to_csv('votes_of_9th_parlament(2019-2020-may).csv',index=False)

In [ ]:
with open("/content/drive/My Drive/Eng/ep_meps.json", "r") as read_file:
    raw_meps_data = json.load(read_file)

In [ ]:
raw_meps_data[699]['Name']
#raw_meps_data[1]['UserID']

In [ ]:
raw_meps_data='a'